version: '3.9'
services:
  app:
    build: .
    container_name: feedback-app
    ports:
      - 3000:3000
    env_file:
      - .env.docker
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: feedback-mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db

volumes:
  mongo-data:
