import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import { Toaster } from "react-hot-toast";
import { Providers } from "./reduxToolkit/provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: " Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* <h1>Practicing Next.js(common layout)</h1> */}
         {/* <Sidebar></Sidebar> */}
         <Toaster position="top-center"></Toaster>
         {/* <Providers>
            {children}
         </Providers> */}
        {children}
      </body>
    </html>
  );
}
